services:
  shortening:
    build: ./URLShorteningService
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - postgres
      - rabbitmq
      - redis

  gateway:
    build: ./OcelotGateway
    ports:
      - "8000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - shortening
      - redirect

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redirect:
    build: ./RedirectService
    ports:
        - "5002:8080"
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
        - redis
        - rabbitmq